name: Create GitHub release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  create_gh_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: steps.validate.outputs.exit_code == 0
        with:
          generate_release_notes: true